### ISSUE TITLE
Empty image response w/ Qwik on Vercel Edge

### ISSUE THREAD

**Issue by flaming-codes** [fabian-hiller/og-img#3]
Hi @fabian-hiller 👋 Many thanks for creating this lib! I noticed an error that I can't resolve, so maybe it's an issue with my setup or a bug.

I'm dynamically generating open graph images in my Qwik City site with [custom endpoints](https://github.com/flaming-codes/flaming-codes-web/blob/main/src/routes/%5B...lang%5D/posts/%5Bslug%5D/og/index.tsx).

This is working fine locally both during development (`npm run dev`) as well as preview (`npm run preview`).

If deployed with the Vercel Edge Network adapter for Qwik City, the response from this endpoint is always empty (but a 200, no error is thrown). Example: [og-image](https://flaming.codes/en/posts/better-documentation-in-ts-and-js-with-rich-metadata/og?title=Better%20documentation%20in%20TS%20%26%20JS). Notice that the response is correctly using `content-type image/png` according to DevTools.

Therefore I'm wondering if I made a mistake (I should be following the guide) or if a deployment on the Vercel Edge network causes the `ImageResponse` to be empty.

---

Edit: do you have a working example with Qwik on Vercel?

**Comment by fabian-hiller** [comment]
Are there any errors in the server log? Can you share your code with me?

**Comment by flaming-codes** [comment]
oh snap, how did I forget that 🤦 

```
CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
```

and

```
CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder
    at (q-u11fv8n2.js:303:7794)
    at (q-u11fv8n2.js:303:9924)
    at (q-u11fv8n2.js:303:10084)
    at (q-u11fv8n2.js:370:29562)
```

WebAssembly [is supported](https://vercel.com/blog/introducing-support-for-webassembly-at-the-edge) by Vercel on Edge. This code should only run on the server, so my CSP shouldn't be the issue (still updated it, but no change).

Will have to look into this more, maybe there's some flag in Vercel I need to enable.

**Comment by fabian-hiller** [comment]
I would recommend you `@vercel/og` but that breaks the build step of Qwik. That's kind of the reason why this library exists.

**Comment by fabian-hiller** [comment]
Could you solve this problem @flaming-codes?

**Comment by tom-bywild** [comment]
Hi, sadly no, but I believe I’ll move away from Vercel for this project anyway, as QwikCity currently only supports deployments to Vercel Edge. This lead to a downgrade in latency and web vitals while also going way over the free tier units. 

I think I’ll move to fly.io, but not sure yet.

**Comment by fabian-hiller** [comment]
This issue can be solved by using `@vercel/og` instead of `og-img` and preventing `@vercel/og` from being bundled by Qwik:
- https://github.com/fabian-hiller/valibot/blob/f4d2544719ea44bd2c7662d8d4a1ece4504fe67a/website/src/routes/og-image/index.ts
- https://github.com/fabian-hiller/valibot/blob/f4d2544719ea44bd2c7662d8d4a1ece4504fe67a/website/adapters/vercel-edge/vite.config.ts
